spring.application.name=vetcare
# Reemplaza puerto, nombre_bd, usuario y password
spring.datasource.url=jdbc:postgresql://localhost:5432/vetcare
spring.datasource.username=postgres
spring.datasource.password=1107849207
spring.datasource.driver-class-name=org.postgresql.Driver

# Mantiene tus tablas intactas sin modificarlas ni borrarlas
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL ejecutadas en consola (opcional)
spring.jpa.show-sql=true